title: "Wallaby"
remote_theme: pmarsceill/just-the-docs

# @see https://pmarsceill.github.io/just-the-docs/docs/configuration/#search
search_enabled: true

# @see https://pmarsceill.github.io/just-the-docs/docs/configuration/#aux-links
aux_links:
  "GitHub":
    - "https://github.com/wallaby-rails/wallaby-core"
